name: App lints check

on:
  push:
    branches: ["master"]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.4"
          channel: "stable"
          cache: true
      - name: Check Flutter version
        run: flutter --version
      - name: Get Dependencies
        run: flutter pub get
      - name: Analyze App
        run: flutter analyze
